In [1]:
import pandas
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.externals import joblib
from sklearn.metrics import accuracy_score

In [2]:
import matplotlib.pyplot as plt

In [3]:
df=pandas.read_csv('./water_amount_data.csv')

In [4]:
X=df[list(df.columns)[:-1]]

In [5]:
Y=df[list(df.columns)[-1]]

In [6]:
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,random_state=0)

In [7]:
linear_reg = LinearRegression()

In [8]:
linear_reg.fit(xtrain, ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [9]:
y_pred = linear_reg.predict(xtest)

In [10]:
ytest

2    10.0
8     8.0
4     6.5
Name: time, dtype: float64

In [11]:
y_pred

array([18.33002826, 11.98575677,  9.54358696])

In [12]:
xtest

temp  humidity  wind
2  27.0        72   7.8
8  25.0        50   4.0
4  20.0        60   4.1

In [13]:
type(ytest)

pandas.core.series.Series

In [14]:
type(y_pred)

numpy.ndarray

In [15]:
type(xtest)

pandas.core.frame.DataFrame

In [25]:
aa = ytest.values

In [26]:
type(aa)

numpy.ndarray

In [29]:
ytest

2    10.0
8     8.0
4     6.5
Name: time, dtype: float64

In [30]:
aa

array([10. ,  8. ,  6.5])

In [31]:
y_pred

array([18.33002826, 11.98575677,  9.54358696])

In [40]:
new_arr_y_pred = np.array([y_pred])
new_arr_y_pred

array([[18.33002826, 11.98575677,  9.54358696]])

In [39]:
new_arr_ytest = np.array([ytest])
new_arr_ytest

array([[10. ,  8. ,  6.5]])

In [41]:
acc = accuracy_score(new_arr_ytest, new_arr_y_pred)

ValueError: continuous-multioutput is not supported

In [42]:
xtest

temp  humidity  wind
2  27.0        72   7.8
8  25.0        50   4.0
4  20.0        60   4.1